[0m00:04:02.438358 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcdeba1b380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcded1f1a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcdea831d10>]}


============================== 00:04:02.443921 | 0e3465eb-d91d-4399-9a49-6ca82bf8fc39 ==============================
[0m00:04:02.443921 [info ] [MainThread]: Running with dbt=1.10.4
[0m00:04:02.444558 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/Viber/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:04:24.573293 [debug] [MainThread]: Starter project path: /home/Viber/taxi_snowflake/venv/lib/python3.13/site-packages/dbt/include/starter_project
[0m00:04:24.576279 [info ] [MainThread]: 
Your new dbt project "nyc_taxi_2024_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:04:24.576883 [info ] [MainThread]: Setting up your profile.
[0m00:07:19.572535 [info ] [MainThread]: Profile nyc_taxi_2024_pipeline written to /home/Viber/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:07:19.739653 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 197.38255, "process_in_blocks": "5704", "process_kernel_time": 0.157475, "process_mem_max_rss": "125032", "process_out_blocks": "80", "process_user_time": 1.896017}
[0m00:07:19.740786 [debug] [MainThread]: Command `dbt init` succeeded at 00:07:19.740601 after 197.38 seconds
[0m00:07:19.741287 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcde9218510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcdeafa39b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcde93f07c0>]}
[0m00:07:19.741738 [debug] [MainThread]: Flushing usage events
[0m00:07:21.460254 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:07:41.904865 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6bdcd3b380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6bde3f1a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6bdbb51d10>]}


============================== 00:07:41.910568 | e749f7c9-446c-4d3d-bb9d-ee0a3dd210e4 ==============================
[0m00:07:41.910568 [info ] [MainThread]: Running with dbt=1.10.4
[0m00:07:41.911406 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/Viber/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:07:41.928878 [info ] [MainThread]: dbt version: 1.10.4
[0m00:07:41.929388 [info ] [MainThread]: python version: 3.13.5
[0m00:07:41.929803 [info ] [MainThread]: python path: /home/Viber/taxi_snowflake/venv/bin/python
[0m00:07:41.930184 [info ] [MainThread]: os info: Linux-6.15.4-arch2-1-x86_64-with-glibc2.41
[0m00:07:42.297991 [info ] [MainThread]: Using profiles dir at /home/Viber/.dbt
[0m00:07:42.298539 [info ] [MainThread]: Using profiles.yml file at /home/Viber/.dbt/profiles.yml
[0m00:07:42.299154 [info ] [MainThread]: Using dbt_project.yml file at /home/Viber/taxi_snowflake/dbt_project.yml
[0m00:07:42.299929 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m00:07:42.301160 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.46286318, "process_in_blocks": "13536", "process_kernel_time": 0.164037, "process_mem_max_rss": "125880", "process_out_blocks": "8", "process_user_time": 1.898747}
[0m00:07:42.302156 [debug] [MainThread]: Command `dbt debug` failed at 00:07:42.301978 after 0.46 seconds
[0m00:07:42.302656 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6bda47a2c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6bda4a9010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6bda440c00>]}
[0m00:07:42.303207 [debug] [MainThread]: Flushing usage events
[0m00:07:43.073567 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:30:47.193829 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f07d2937380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f07d4039bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f07d177bc50>]}


============================== 01:30:47.212654 | c6885f22-91e8-4a08-944a-a0d4b6c67def ==============================
[0m01:30:47.212654 [info ] [MainThread]: Running with dbt=1.10.4
[0m01:30:47.214357 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/Viber/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt deps', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:30:47.216083 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/Viber/taxi_snowflake/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:30:47.218880 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.114501946, "process_in_blocks": "68592", "process_kernel_time": 0.214378, "process_mem_max_rss": "99696", "process_out_blocks": "8", "process_user_time": 2.152749}
[0m01:30:47.220302 [debug] [MainThread]: Command `dbt deps` failed at 01:30:47.219947 after 0.12 seconds
[0m01:30:47.222197 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f07d17722c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f07d184b770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f07d1a18e20>]}
[0m01:30:47.227486 [debug] [MainThread]: Flushing usage events
[0m01:30:48.090459 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:36:57.224967 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2e6763b380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2e68d61bd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2e6647fc50>]}


============================== 01:36:57.229783 | c28d50fb-9cf8-4aa8-96b5-3b334d00bf69 ==============================
[0m01:36:57.229783 [info ] [MainThread]: Running with dbt=1.10.4
[0m01:36:57.230677 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/home/Viber/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run -s stg_fact_table+', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m01:36:57.231333 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/Viber/taxi_snowflake/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:36:57.232555 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.07421421, "process_in_blocks": "0", "process_kernel_time": 0.125709, "process_mem_max_rss": "100216", "process_out_blocks": "8", "process_user_time": 1.828349}
[0m01:36:57.233261 [debug] [MainThread]: Command `dbt run` failed at 01:36:57.233118 after 0.08 seconds
[0m01:36:57.233777 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2e664762c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2e66547770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2e6671cd10>]}
[0m01:36:57.234279 [debug] [MainThread]: Flushing usage events
[0m01:36:58.063217 [debug] [MainThread]: An error was encountered while trying to flush usage events
